### ISSUE TITLE
Client Absturz

### ISSUE THREAD

**Issue by authaldo** [SoPra-Team-17/Client#136]
xhost local:docker
non-network local connections being added to access control list
docker run --rm --volume="/home/dominik/.Xauthority:/root/.Xauthority:rw" --env="DISPLAY" --net=host soprateam17/client
libpng warning: iCCP: known incorrect sRGB profile
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
2020-06-08 18:47:14,256 [MainThread  ] [INFO    ] [MainMenuScreen.py    - __init__             - 42  ] MainMenuScreen init done
2020-06-08 18:47:14,315 [MainThread  ] [INFO    ] [SettingsScreen.py    - __init__             - 67  ] Settings Screen init done
2020-06-08 18:47:14,578 [MainThread  ] [INFO    ] [HelpScreen.py        - __init__             - 44  ] Help Screen init done
2020-06-08 18:47:14,578 [MainThread  ] [INFO    ] [MainMenuView.py      - __init__             - 29  ] MainMenu init done
2020-06-08 18:47:15,083 [MainThread  ] [INFO    ] [HUDScreen.py         - __init__             - 79  ] HudScreen init done
2020-06-08 18:47:15,083 [MainThread  ] [INFO    ] [HUDView.py           - __init__             - 21  ] HUDView init done
2020-06-08 18:47:15,091 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - __init__             - 90  ] Itemchoice init done
2020-06-08 18:47:15,103 [MainThread  ] [INFO    ] [EquipmentScreen.py   - __init__             - 91  ] Equipment screen init done
2020-06-08 18:47:15,135 [MainThread  ] [INFO    ] [LobbyScreen.py       - __init__             - 46  ] Lobbyscreen init done
2020-06-08 18:47:15,135 [MainThread  ] [INFO    ] [LobbyView.py         - __init__             - 28  ] Lobby init done
2020-06-08 18:47:15,135 [MainThread  ] [INFO    ] [Controller.py        - init_components      - 76  ] Controller init done
2020-06-08 18:47:19,200 [MainThread  ] [INFO    ] [SettingsScreen.py    - return_button_presse - 124 ] WindowName: No Time to Spy
Resolution: 1920x1080
Frame rate: 60
Audio effects: 50.0 Music: 50.0
Server address: 134.60.154.237 Port: 7007
Max reconnects: 25

2020-06-08 18:47:20,084 [MainThread  ] [INFO    ] [Controller.py        - to_lobby_view        - 123 ] Active view: lobby view
2020-06-08 18:47:24,031 [MainThread  ] [INFO    ] [LibClientHandler.py  - sendHello            - 43  ] Send Hello Message: Name: Dominik Role: 2
2020-06-08 18:47:24,038 [MainThread  ] [INFO    ] [LobbyScreen.py       - connect_pressed      - 77  ] Sending Hello successfull: True
2020-06-08 18:47:24,105 [Dummy-1     ] [INFO    ] [Callback.py          - onHelloReply         - 24  ] Received Hello Reply
2020-06-08 18:47:24,106 [Dummy-1     ] [INFO    ] [Callback.py          - onGameStarted        - 28  ] Received GameStarted
2020-06-08 18:47:24,106 [Dummy-1     ] [INFO    ] [Callback.py          - onRequestItemChoice  - 32  ] Received Request Item Choice
2020-06-08 18:47:24,113 [MainThread  ] [INFO    ] [LobbyView.py         - receive_event        - 39  ] Go to Item Choice Phase
2020-06-08 18:47:24,113 [MainThread  ] [INFO    ] [Controller.py        - to_game_view         - 131 ] Active view: game view
2020-06-08 18:47:24,363 [MainThread  ] [INFO    ] [Controller.py        - to_game_view         - 138 ] Send Request Metainformation successfull: True
2020-06-08 18:47:25,103 [Dummy-1     ] [INFO    ] [Callback.py          - onMetaInformation    - 60  ] Received Meta Information
2020-06-08 18:47:27,444 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - selected_item        - 145 ] Gadget: True Index: 2
2020-06-08 18:47:28,097 [Dummy-1     ] [INFO    ] [Callback.py          - onRequestItemChoice  - 32  ] Received Request Item Choice
2020-06-08 18:47:28,099 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - receive_event        - 119 ] Update selection based on new Item Choices
2020-06-08 18:48:18,555 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - selected_item        - 145 ] Gadget: False Index: 2
2020-06-08 18:48:19,144 [Dummy-1     ] [INFO    ] [Callback.py          - onRequestItemChoice  - 32  ] Received Request Item Choice
2020-06-08 18:48:19,146 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - receive_event        - 119 ] Update selection based on new Item Choices
2020-06-08 18:48:26,548 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - selected_item        - 145 ] Gadget: False Index: 2
2020-06-08 18:48:27,150 [Dummy-1     ] [INFO    ] [Callback.py          - onRequestItemChoice  - 32  ] Received Request Item Choice
2020-06-08 18:48:27,161 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - receive_event        - 119 ] Update selection based on new Item Choices
2020-06-08 18:48:36,380 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - selected_item        - 145 ] Gadget: False Index: 0
2020-06-08 18:48:37,155 [Dummy-1     ] [INFO    ] [Callback.py          - onRequestItemChoice  - 32  ] Received Request Item Choice
2020-06-08 18:48:37,160 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - receive_event        - 119 ] Update selection based on new Item Choices
2020-06-08 18:48:38,496 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - selected_item        - 145 ] Gadget: True Index: 1
2020-06-08 18:48:39,154 [Dummy-1     ] [INFO    ] [Callback.py          - onRequestItemChoice  - 32  ] Received Request Item Choice
2020-06-08 18:48:39,155 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - receive_event        - 119 ] Update selection based on new Item Choices
2020-06-08 18:48:46,444 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - selected_item        - 145 ] Gadget: False Index: 2
2020-06-08 18:48:47,161 [Dummy-1     ] [INFO    ] [Callback.py          - onRequestItemChoice  - 32  ] Received Request Item Choice
2020-06-08 18:48:47,168 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - receive_event        - 119 ] Update selection based on new Item Choices
2020-06-08 18:48:51,042 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - selected_item        - 145 ] Gadget: True Index: 0
2020-06-08 18:48:51,164 [Dummy-1     ] [INFO    ] [Callback.py          - onRequestItemChoice  - 32  ] Received Request Item Choice
2020-06-08 18:48:51,171 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - receive_event        - 119 ] Update selection based on new Item Choices
2020-06-08 18:48:53,403 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - selected_item        - 145 ] Gadget: True Index: 1
2020-06-08 18:48:54,169 [Dummy-1     ] [INFO    ] [Callback.py          - onRequestEquipmentCh - 36  ] Received Request Equipment Choice
2020-06-08 18:48:54,172 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - receive_event        - 122 ] Entering equipment choice phase
2020-06-08 18:48:58,417 [MainThread  ] [INFO    ] [EquipmentScreen.py   - _send_selection      - 133 ] Sending map to server
{<cppyy.gbl.spy.util.UUID object at 0x7a1ef50>: [17], <cppyy.gbl.spy.util.UUID object at 0x7a1ef60>: [15], <cppyy.gbl.spy.util.UUID object at 0x7a1ef70>: [4], <cppyy.gbl.spy.util.UUID object at 0x7a1ef80>: [12]}
2020-06-08 18:48:58,911 [MainThread  ] [INFO    ] [EquipmentScreen.py   - _send_selection      - 136 ] Send equipment choice message successfull: True
2020-06-08 18:49:14,786 [Dummy-1     ] [INFO    ] [Callback.py          - onGameStatus         - 40  ] Received Game Status
2020-06-08 18:49:14,787 [Dummy-1     ] [INFO    ] [Callback.py          - onRequestGameOperati - 44  ] Received Request Game Operation
2020-06-08 18:49:14,797 [MainThread  ] [INFO    ] [EquipmentScreen.py   - receive_event        - 117 ] Go to playing field
2020-06-08 18:49:14,937 [MainThread  ] [INFO    ] [PlayingFieldScreen.p - update_playingfield  - 153 ] Successfully updated playing field
2020-06-08 18:49:27,548 [MainThread  ] [WARNING ] [HUDScreen.py         - receive_event        - 102 ] Element not found in dict
2020-06-08 18:49:30,204 [MainThread  ] [WARNING ] [HUDScreen.py         - receive_event        - 102 ] Element not found in dict
2020-06-08 18:49:31,461 [MainThread  ] [WARNING ] [HUDScreen.py         - receive_event        - 102 ] Element not found in dict
PosX: 13	PosY: 3
2020-06-08 18:49:34,491 [MainThread  ] [INFO    ] [SelectionInfoBox.py  - __create_field_info_ - 128 ] Updating field info string
2020-06-08 18:50:02,724 [MainThread  ] [WARNING ] [HUDScreen.py         - receive_event        - 102 ] Element not found in dict
2020-06-08 18:50:04,081 [MainThread  ] [WARNING ] [HUDScreen.py         - receive_event        - 102 ] Element not found in dict
PosX: 14	PosY: 7
2020-06-08 18:50:10,938 [MainThread  ] [INFO    ] [SelectionInfoBox.py  - __create_field_info_ - 128 ] Updating field info string
2020-06-08 18:50:13,436 [MainThread  ] [INFO    ] [HUDScreen.py         - send_action_pressed  - 130 ] Send Movement successfull: True
2020-06-08 18:50:14,285 [Dummy-1     ] [INFO    ] [Callback.py          - onGameStatus         - 40  ] Received Game Status
2020-06-08 18:50:14,286 [Dummy-1     ] [INFO    ] [Callback.py          - onRequestGameOperati - 44  ] Received Request Game Operation
2020-06-08 18:50:14,306 [MainThread  ] [INFO    ] [PlayingFieldScreen.p - update_playingfield  - 153 ] Successfully updated playing field
PosX: 14	PosY: 6
2020-06-08 18:50:23,400 [MainThread  ] [INFO    ] [SelectionInfoBox.py  - __create_field_info_ - 128 ] Updating field info string
2020-06-08 18:50:24,305 [MainThread  ] [INFO    ] [HUDScreen.py         - send_action_pressed  - 130 ] Send Movement successfull: True
2020-06-08 18:50:25,294 [Dummy-1     ] [INFO    ] [Callback.py          - onGameStatus         - 40  ] Received Game Status
2020-06-08 18:50:25,294 [Dummy-1     ] [INFO    ] [Callback.py          - onRequestGameOperati - 44  ] Received Request Game Operation
2020-06-08 18:50:25,319 [MainThread  ] [INFO    ] [PlayingFieldScreen.p - update_playingfield  - 153 ] Successfully updated playing field
PosX: 14	PosY: 5
2020-06-08 18:50:26,239 [MainThread  ] [INFO    ] [SelectionInfoBox.py  - __create_field_info_ - 128 ] Updating field info string
2020-06-08 18:50:27,696 [MainThread  ] [INFO    ] [HUDScreen.py         - send_action_pressed  - 130 ] Send Movement successfull: True
2020-06-08 18:50:28,303 [Dummy-1     ] [INFO    ] [Callback.py          - onGameStatus         - 40  ] Received Game Status
2020-06-08 18:50:28,306 [Dummy-1     ] [INFO    ] [Callback.py          - onRequestGameOperati - 44  ] Received Request Game Operation
2020-06-08 18:50:28,324 [MainThread  ] [INFO    ] [PlayingFieldScreen.p - update_playingfield  - 153 ] Successfully updated playing field
2020-06-08 18:50:33,091 [MainThread  ] [WARNING ] [HUDScreen.py         - receive_event        - 102 ] Element not found in dict
2020-06-08 18:50:34,260 [MainThread  ] [WARNING ] [HUDScreen.py         - receive_event        - 102 ] Element not found in dict
2020-06-08 18:50:36,964 [MainThread  ] [INFO    ] [HUDScreen.py         - send_action_pressed  - 137 ] Send Retire Action successfull: True
2020-06-08 18:50:37,340 [Dummy-1     ] [INFO    ] [Callback.py          - onGameStatus         - 40  ] Received Game Status
2020-06-08 18:50:37,356 [Dummy-1     ] [INFO    ] [Callback.py          - onGameStatus         - 40  ] Received Game Status
2020-06-08 18:50:37,382 [MainThread  ] [INFO    ] [PlayingFieldScreen.p - update_playingfield  - 153 ] Successfully updated playing field
2020-06-08 18:50:37,416 [Dummy-1     ] [INFO    ] [Callback.py          - onGameStatus         - 40  ] Received Game Status
2020-06-08 18:50:37,439 [Dummy-1     ] [INFO    ] [Callback.py          - onGameStatus         - 40  ] Received Game Status
2020-06-08 18:50:37,471 [Dummy-1     ] [INFO    ] [Callback.py          - onGameStatus         - 40  ] Received Game Status
2020-06-08 18:50:37,472 [Dummy-1     ] [INFO    ] [Callback.py          - onGamePause          - 56  ] Received Game Pause
2020-06-08 18:50:37,558 [MainThread  ] [INFO    ] [PlayingFieldScreen.p - update_playingfield  - 153 ] Successfully updated playing field
2020-06-08 18:50:37,792 [MainThread  ] [INFO    ] [PlayingFieldScreen.p - update_playingfield  - 153 ] Successfully updated playing field
2020-06-08 18:50:37,871 [Dummy-1     ] [INFO    ] [Callback.py          - connectionLost       - 76  ] Received Connectin lost
2020-06-08 18:50:37,965 [MainThread  ] [INFO    ] [PlayingFieldScreen.p - update_playingfield  - 153 ] Successfully updated playing field
2020-06-08 18:50:38,130 [MainThread  ] [INFO    ] [PlayingFieldScreen.p - update_playingfield  - 153 ] Successfully updated playing field
/usr/local/lib/python3.6/dist-packages/pygame_gui/core/ui_font_dictionary.py:155: UserWarning: Finding font with id: fira_code_bold_14 that is not already loaded.
Preload this font with {'name': 'fira_code', 'point_size': 14, 'style': 'bold'}
  warnings.warn(warning_string, UserWarning)
/usr/local/lib/python3.6/dist-packages/pygame_gui/core/ui_font_dictionary.py:155: UserWarning: Finding font with id: fira_code_bold_14 that is not already loaded.
Preload this font with {'name': 'fira_code', 'point_size': 14, 'style': 'bold'}
  warnings.warn(warning_string, UserWarning)
Traceback (most recent call last):
  File "run.py", line 46, in <module>
    main()
  File "run.py", line 42, in main
    controller.loop()
  File "/client/controller/Controller.py", line 92, in loop
    view.receive_event(event)
  File "/client/view/GameView/GameView.py", line 54, in receive_event
    view.receive_event(event)
  File "/client/view/GameView/HUDView.py", line 29, in receive_event
    screen.receive_event(event)
  File "/client/view/GameView/HUDScreen.py", line 109, in receive_event
    self.selection_info_box.update_textbox()
TypeError: update_textbox() missing 3 required positional arguments: 'gadget_icon_list', 'property_icon_list', and 'selected_gad_prop_idx'
Makefile:7: recipe for target 'run' failed
make: *** [run] Error 1

**Comment by Marco5de** [comment]
`update_textbox()` wurde noch mit alter Signatur aufgerufen.
Ist im aktuellen develop bereits gefixed.
