### ISSUE TITLE
Absturz bei Pause

### ISSUE THREAD

**Issue by ottojo** [SoPra-Team-17/Client#137]
Absturz mit folgendem log wenn Server Pause sendet:
```
2020-06-08 19:55:22,089 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - receive_event        - 119 ] Update selection based on new Item Choices
2020-06-08 19:55:22,413 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - selected_item        - 145 ] Gadget: True Index: 1
2020-06-08 19:55:23,077 [Dummy-1     ] [INFO    ] [Callback.py          - onRequestItemChoice  - 32  ] Received Request Item Choice
2020-06-08 19:55:23,089 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - receive_event        - 119 ] Update selection based on new Item Choices
2020-06-08 19:55:23,588 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - selected_item        - 145 ] Gadget: True Index: 1
2020-06-08 19:55:32,606 [Dummy-1     ] [INFO    ] [Callback.py          - onRequestEquipmentCh - 36  ] Received Request Equipment Choice
2020-06-08 19:55:32,619 [MainThread  ] [INFO    ] [ItemChoiceScreen.py  - receive_event        - 122 ] Entering equipment choice phase
2020-06-08 19:55:39,802 [MainThread  ] [INFO    ] [EquipmentScreen.py   - _send_selection      - 133 ] Sending map to server
{<cppyy.gbl.spy.util.UUID object at 0x821c9a0>: [5], <cppyy.gbl.spy.util.UUID object at 0x821c9b0>: [12], <cppyy.gbl.spy.util.UUID object at 0x821c9c0>: [10], <cppyy.gbl.spy.util.UUID object at 0x821c9d0>: [13]}
2020-06-08 19:55:40,136 [MainThread  ] [INFO    ] [EquipmentScreen.py   - _send_selection      - 136 ] Send equipment choice message successfull: True
2020-06-08 19:55:41,106 [Dummy-1     ] [INFO    ] [Callback.py          - onGameStatus         - 40  ] Received Game Status
2020-06-08 19:55:41,107 [Dummy-1     ] [INFO    ] [Callback.py          - onRequestGameOperati - 44  ] Received Request Game Operation
2020-06-08 19:55:41,107 [MainThread  ] [INFO    ] [EquipmentScreen.py   - receive_event        - 117 ] Go to playing field
2020-06-08 19:55:41,216 [MainThread  ] [INFO    ] [PlayingFieldScreen.p - update_playingfield  - 153 ] Successfully updated playing field
2020-06-08 19:55:44,619 [Dummy-1     ] [INFO    ] [Callback.py          - onGamePause          - 56  ] Received Game Pause
/usr/local/lib/python3.6/dist-packages/pygame_gui/core/ui_font_dictionary.py:155: UserWarning: Finding font with id: fira_code_bold_14 that is not already loaded.
Preload this font with {'name': 'fira_code', 'point_size': 14, 'style': 'bold'}
  warnings.warn(warning_string, UserWarning)
Traceback (most recent call last):
  File "run.py", line 46, in <module>
    main()
  File "run.py", line 42, in main
    controller.loop()
  File "/client/controller/Controller.py", line 92, in loop
    view.receive_event(event)
  File "/client/view/GameView/GameView.py", line 54, in receive_event
    view.receive_event(event)
  File "/client/view/GameView/HUDView.py", line 29, in receive_event
    screen.receive_event(event)
  File "/client/view/GameView/HUDScreen.py", line 109, in receive_event
    self.selection_info_box.update_textbox()
TypeError: update_textbox() missing 3 required positional arguments: 'gadget_icon_list', 'property_icon_list', and 'selected_gad_prop_idx'
make: *** [Makefile:8: run] Error 1
```

**Comment by Marco5de** [comment]
` update_textbox()` wurde noch mit alter Signatur aufgerufen. Ist im aktuellen develop bereits gefixed.
